import type { Orientation } from '../types/tarot'

export interface CardMeanings {
  upright: string
  reversed: string
}

export const cardMeanings = {
  'the-fool': { upright: 'New beginnings, openness, and a willingness to explore.', reversed: 'Pause before a leap; uncertainty or avoidable risk may need attention.' },
  'the-magician': { upright: 'Use your skills and available resources with clear intention.', reversed: 'Scattered effort or unused abilities may be getting in the way.' },
  'the-high-priestess': { upright: 'Listen inwardly and allow what is not yet clear to unfold.', reversed: 'Noise, withheld information, or ignored intuition may cloud the picture.' },
  'the-empress': { upright: 'Nurture growth, creativity, and the care that helps things flourish.', reversed: 'Consider where care is depleted, overextended, or difficult to receive.' },
  'the-emperor': { upright: 'Steady structure, boundaries, and responsibility can support progress.', reversed: 'Rigid control or weak boundaries may call for a more balanced approach.' },
  'the-hierophant': { upright: 'Learning, shared values, or established guidance may be useful.', reversed: 'Question whether inherited rules still fit your values and needs.' },
  'the-lovers': { upright: 'A meaningful choice or relationship invites honesty and alignment.', reversed: 'Notice mismatched values, unclear choices, or a need for self-honesty.' },
  'the-chariot': { upright: 'Focused resolve can help bring competing forces into alignment.', reversed: 'Scattered direction or forceful control may be slowing your progress.' },
  strength: { upright: 'Meet difficulty with patience, courage, and gentle self-command.', reversed: 'Self-doubt or frustration may be asking for compassion and steadiness.' },
  'the-hermit': { upright: 'Quiet reflection can help you find your own considered direction.', reversed: 'Too much withdrawal or outside noise may be obscuring what you know.' },
  'wheel-of-fortune': { upright: 'A turning point invites adaptability and awareness of changing cycles.', reversed: 'Delays or resistance may call for flexibility around what you cannot control.' },
  justice: { upright: 'Seek fairness, clear facts, and accountability in your choices.', reversed: 'Look for imbalance, missing information, or responsibility left unclaimed.' },
  'the-hanged-man': { upright: 'A pause or changed perspective may reveal another way forward.', reversed: 'Stalling or clinging to one viewpoint may be costing you movement.' },
  death: { upright: 'An ending can make room for a necessary transition and renewal.', reversed: 'Resistance to change or an unfinished ending may deserve attention.' },
  temperance: { upright: 'Patience and thoughtful blending can restore balance over time.', reversed: 'Excess, impatience, or competing needs may be disrupting your balance.' },
  'the-devil': { upright: 'Notice attachments or patterns that limit your sense of choice.', reversed: 'A restriction may be loosening as you recognize your options.' },
  'the-tower': { upright: 'A disruption can expose what was unstable and needs rebuilding.', reversed: 'Avoiding a needed change may prolong tension; rebuild carefully.' },
  'the-star': { upright: 'Renewed hope and openness can support healing and a wider view.', reversed: 'Discouragement may be dimming hope; make space for gentle renewal.' },
  'the-moon': { upright: 'Move patiently through uncertainty and check what is assumption.', reversed: 'Confusion may be easing, or an overlooked concern may need naming.' },
  'the-sun': { upright: 'Clarity, warmth, and shared vitality are available to be welcomed.', reversed: 'A bright moment may be muted by strain or expectations; seek simple joy.' },
  judgement: { upright: 'Reflection and honest reckoning can help you answer a new call.', reversed: 'Harsh self-judgment or avoidance may make it harder to move on.' },
  'the-world': { upright: 'A cycle nears completion; recognize what you have brought together.', reversed: 'A lingering detail or unfinished step may stand between you and closure.' },
  'ace-of-wands': { upright: 'A spark of inspiration or desire offers energy for a fresh start.', reversed: 'Low momentum or a delayed spark may call for patience and reconnection.' },
  'two-of-wands': { upright: 'Consider your options and make a plan beyond familiar ground.', reversed: 'Fear of the unknown or a narrow plan may be limiting your choices.' },
  'three-of-wands': { upright: 'Look ahead and stay open to results from steps already taken.', reversed: 'Delays or limited foresight may call for adjusting your expectations.' },
  'four-of-wands': { upright: 'Mark a milestone and draw strength from belonging or support.', reversed: 'Tension at home or an unsettled milestone may need care.' },
  'five-of-wands': { upright: 'Different aims create friction; engage the challenge constructively.', reversed: 'Conflict may be settling, or unspoken tensions may remain.' },
  'six-of-wands': { upright: 'Acknowledge progress and accept recognition with humility.', reversed: 'Unseen effort or dependence on approval may affect confidence.' },
  'seven-of-wands': { upright: 'Stand by what matters while choosing your boundaries carefully.', reversed: 'Exhaustion or defensiveness may be making it hard to hold your ground.' },
  'eight-of-wands': { upright: 'Momentum is building; clear communication can help things move.', reversed: 'Delays or crossed messages may call for a pause and a clearer plan.' },
  'nine-of-wands': { upright: 'Stay resilient while protecting the limits you have learned to set.', reversed: 'Weariness or guardedness may be a sign to rest and reassess.' },
  'ten-of-wands': { upright: 'A heavy load may be nearing its end; review what you can share.', reversed: 'Overload or reluctance to delegate may be ready for change.' },
  'page-of-wands': { upright: 'Curiosity and enthusiasm invite an exploratory first step.', reversed: 'Restlessness or hesitation may need direction before acting.' },
  'knight-of-wands': { upright: 'Act boldly on inspiration while staying aware of your pace.', reversed: 'Impulsiveness or stop-start energy may benefit from a steadier course.' },
  'queen-of-wands': { upright: 'Bring warmth, confidence, and creative independence to the moment.', reversed: 'Self-consciousness or overextension may be dimming your natural spark.' },
  'king-of-wands': { upright: 'Lead with vision and encourage others through purposeful action.', reversed: 'Impatience or domineering plans may need more listening and flexibility.' },
  'ace-of-cups': { upright: 'Emotional openness makes room for connection, care, or renewal.', reversed: 'Feelings may be held back or running low; tend to your inner needs.' },
  'two-of-cups': { upright: 'Mutual respect and honest exchange can strengthen a connection.', reversed: 'An imbalance or misunderstanding may need open conversation.' },
  'three-of-cups': { upright: 'Shared joy and friendship offer support worth celebrating.', reversed: 'Social strain or overindulgence may call for a healthier balance.' },
  'four-of-cups': { upright: 'A pause can clarify what you truly want to accept or pursue.', reversed: 'Renewed interest may be possible as you reengage with what is offered.' },
  'five-of-cups': { upright: 'Grief deserves room, alongside awareness of what remains.', reversed: 'Healing may begin as you turn toward support and possibility.' },
  'six-of-cups': { upright: 'Memory, kindness, or familiar comforts can offer perspective.', reversed: 'The past may be hard to release, or growth may ask you to move beyond it.' },
  'seven-of-cups': { upright: 'Many appealing possibilities call for discernment and grounded choice.', reversed: 'Fog may be clearing; focus on the option that fits your real priorities.' },
  'eight-of-cups': { upright: 'It may be time to leave what no longer feels meaningful and seek more.', reversed: 'Uncertainty about leaving or returning may need honest reflection.' },
  'nine-of-cups': { upright: 'Enjoy what is satisfying while noticing what would feel fulfilling.', reversed: 'A wish may not satisfy as expected; revisit what you truly value.' },
  'ten-of-cups': { upright: 'Emotional belonging and shared well-being are worth tending.', reversed: 'Strain in a group or idealized expectations may need candid care.' },
  'page-of-cups': { upright: 'Stay receptive to tenderness, imagination, and new emotional insight.', reversed: 'Emotional uncertainty or sensitivity may call for gentle grounding.' },
  'knight-of-cups': { upright: 'Follow a heartfelt invitation while keeping your expectations clear.', reversed: 'Idealization or shifting moods may blur what is being offered.' },
  'queen-of-cups': { upright: 'Meet feelings with empathy while honoring your own emotional limits.', reversed: 'Emotional overwhelm or porous boundaries may need steady care.' },
  'king-of-cups': { upright: 'Balance compassion with calm judgment and emotional steadiness.', reversed: 'Suppressed or changeable feelings may be affecting your decisions.' },
  'ace-of-swords': { upright: 'A clear idea or honest conversation can cut through uncertainty.', reversed: 'Confusion or untested assumptions may call for careful fact-checking.' },
  'two-of-swords': { upright: 'A difficult choice may need quiet, balanced consideration.', reversed: 'Avoidance or too much information may be keeping a choice stuck.' },
  'three-of-swords': { upright: 'A painful truth or disappointment deserves acknowledgment and care.', reversed: 'The hurt may be easing, though healing can take time and support.' },
  'four-of-swords': { upright: 'Rest and mental space can help restore perspective.', reversed: 'Restlessness or returning too soon may be draining your reserves.' },
  'five-of-swords': { upright: 'Consider the cost of winning and whether conflict can be resolved.', reversed: 'Repair may be possible, or lingering resentment may need to be addressed.' },
  'six-of-swords': { upright: 'A gradual transition can move you toward calmer conditions.', reversed: 'Moving on may feel difficult; notice what still needs attention.' },
  'seven-of-swords': { upright: 'Use discretion and examine whether a strategy is fair and sound.', reversed: 'A hidden issue may surface, or it may be time for greater honesty.' },
  'eight-of-swords': { upright: 'A sense of being trapped may shift as you identify available choices.', reversed: 'You may be finding a way past limits that once felt fixed.' },
  'nine-of-swords': { upright: 'Worry is weighing heavily; separate feared outcomes from present facts.', reversed: 'Anxiety may be easing, or it may be time to seek support with it.' },
  'ten-of-swords': { upright: 'A painful chapter may have reached its limit; allow recovery to begin.', reversed: 'Recovery is possible, though resisting an ending can prolong it.' },
  'page-of-swords': { upright: 'Ask clear questions and stay curious while checking what you hear.', reversed: 'Hasty words or scattered information may need a second look.' },
  'knight-of-swords': { upright: 'Move decisively toward a clear aim while considering the impact.', reversed: 'Rushing or arguing may cloud your judgment; slow down and listen.' },
  'queen-of-swords': { upright: 'Use discernment and direct communication with compassion.', reversed: 'Harshness or guardedness may be hiding a need for clearer boundaries.' },
  'king-of-swords': { upright: 'Bring reason, fairness, and clear principles to your decisions.', reversed: 'Rigid judgment or misuse of authority may call for scrutiny.' },
  'ace-of-pentacles': { upright: 'A practical opportunity can take root with care and follow-through.', reversed: 'A shaky plan or overlooked detail may need grounding before commitment.' },
  'two-of-pentacles': { upright: 'Adaptability can help you balance changing practical demands.', reversed: 'Too many demands or poor prioritization may be stretching you thin.' },
  'three-of-pentacles': { upright: 'Skill and cooperation can turn a shared plan into solid work.', reversed: 'Unclear roles or overlooked contributions may hinder teamwork.' },
  'four-of-pentacles': { upright: 'Protect what matters while staying open to measured change.', reversed: 'Holding too tightly or spending freely may call for balance.' },
  'five-of-pentacles': { upright: 'A period of scarcity or exclusion asks for support and practical care.', reversed: 'Help may be closer than it seems as you begin rebuilding.' },
  'six-of-pentacles': { upright: 'Generosity and fair exchange can strengthen mutual support.', reversed: 'Unequal giving or strings attached may need to be brought into balance.' },
  'seven-of-pentacles': { upright: 'Review your progress and give worthwhile efforts time to mature.', reversed: 'Frustration with slow returns may invite a practical reassessment.' },
  'eight-of-pentacles': { upright: 'Patient practice and attention to detail build lasting skill.', reversed: 'Repetition without care or perfectionism may be draining your effort.' },
  'nine-of-pentacles': { upright: 'Recognize the independence and comfort built through steady effort.', reversed: 'Dependence or fragile security may call for a more grounded plan.' },
  'ten-of-pentacles': { upright: 'Long-term stability grows through shared resources and lasting bonds.', reversed: 'Family or financial expectations may need a more flexible foundation.' },
  'page-of-pentacles': { upright: 'A practical learner’s mindset can turn an idea into a real beginning.', reversed: 'Distraction or an unsteady plan may need renewed commitment.' },
  'knight-of-pentacles': { upright: 'Consistency and care can carry a practical commitment forward.', reversed: 'Stubborn routine or delay may call for a more responsive approach.' },
  'queen-of-pentacles': { upright: 'Grounded care can support both everyday needs and future growth.', reversed: 'Overgiving or neglecting your own resources may need correction.' },
  'king-of-pentacles': { upright: 'Steward resources responsibly and build stability with patience.', reversed: 'Material pressure or inflexibility may be crowding out what matters.' },
} satisfies Record<string, CardMeanings>

export function getCardMeaning(cardId: string, orientation: Orientation): string | undefined {
  return cardMeanings[cardId as keyof typeof cardMeanings]?.[orientation]
}
